###
# @Author: Qizhang Jia
# @Date: 2021-01-19 23:39:52
# @Last Modified by:   Qizhang Jia
# @Last Modified time: 2021-01-19 23:39:52
###

# Counting DNA Nucleotides
Nucleotides = ['A', 'T', 'C', 'G']


def countNucFrequency(dna_seq):
    tmpFreqDict = {'A': 0, 'T': 0, 'C': 0, 'G': 0}
    for nuc in dna_seq:
        tmpFreqDict[nuc] += 1
    return tmpFreqDict


dna_seq = 'TACAACTCTGAATTCCCCAAGTTGTTGGGAATACACATTGATTACAGATCAACCGCGCCGATGAGAACACCGTAACGCTGTCGACTCAGCCCATGACGTCCGCACGTACCTGTGTTAACTTCCGCGTGCAGCACGTGTCGAGGTCAAAGTGTCGTACGAAGCCGCCGGTGACCGAACTTAGGCCCTTTCTGCACGGATTGCAAGCACAGGCGGGTCCTCAAAACAGGCGATAGGACTCAAGGAGGACAACACTTTTGAGGGGCTTTTCAGGCGCAGACGCGCTCGCGCATCCAAAGACGATGGCGCATCTACATAAAGATTCTTCCGACTCCTCCGCGACATAATTGGTGCCCCCAAGTAGACCGTACAACAATCCTCACTATACTGTACGCAAATCTGATGGGGGGGTCGTGTAGCCTATACTCGCGGCGCATACGTACCCTCCTCGACATTTCCACGTAATCAACCCCATTAAATTGCTCCTCCCATGCTGAGATCGCAAGCGTTGGCTAGGTCTGAGTGGGACAGTGATCGGACAACTTTGGCGATGCTCACAGGTCAGATGCTTGAGCCTATAAATGTCGTCAAATACCAGGTCGAGTTGCCGGGGAATGGTACGTAAGCTTAGGCTTACGTGGTCGTGCTAAAGCAAAATCGACGTTCCCTAAATCCAAGCTGTCGAATCGGGCCCTCTGCGGGACAACAATACCAACCGCGAAGCTTGATCTCTGGCAACTCTTCTGGTACGAGAAACGTTTCTTATTGTCAATTCCAAACCCAACAGCCTTGTGCCGTCCCAGCGGTATGAACGGTATGGGAGGGTCGCCCAAGGTCCCCGAGAAGTATCTGCGCCAGGAAACGTACAGTAGAATCGCAACACTTCTTTTCACGCATGAACCTGAGTTG'
freq_dict = countNucFrequency(dna_seq)
print('{} {} {} {}'.format(freq_dict['A'],
                           freq_dict['C'],
                           freq_dict['G'],
                           freq_dict['T']))
